geminirag/urls.py
from django.contrib import admin
from django.urls import path, include

import rag.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("rag.urls"))
]

rag/urls.py
from django.urls import path, include
from . import views

app_name = 'rag'
urlpatterns = [
    path('', views.index, name = 'index' ),
    # path('load/', views.load, name = 'load' ),
    path('llmquiz/', views.llm_quiz, name = 'llm_quiz' ),
    path('select/', views.select, name = 'select' )
]

rag/models.py
from django.db import models

# Create your models here.

rag/views.py
from django.shortcuts import render

import os

# from langchain import PromptTemplate
from langchain_core.prompts import PromptTemplate
from langchain.schema import StrOutputParser
from langchain.schema.runnable import RunnablePassthrough

from langchain_google_genai import GoogleGenerativeAIEmbeddings

from langchain_qdrant import Qdrant
from qdrant_client import QdrantClient
from langchain_google_genai import ChatGoogleGenerativeAI

def index(request):
    context = {}
    return render(request, 'rag/index.html', context)


def llm_quiz(request):
    if request.method == 'POST':
        question_text = request.POST.get('question_text')
        
        rag_ans = ask_rag(question_text)
        simplellm_ans = ask_simple_llm(question_text)      
            
        context = {
            "rag_ans": rag_ans,
            "simplellm_ans":simplellm_ans,
            "question_text":question_text,
                }
        return render(request, "rag/qa.html", context) 
    else:
        rag_ans=""
        simplellm_ans=""
        question_text = ""
        
        context = {
            "rag_ans": rag_ans,
            "simplellm_ans":simplellm_ans,
            "question_text":question_text,
                }
        return render(request, "rag/qa.html", context)
    

def ask_simple_llm(question_text):
    os.environ["GOOGLE_API_KEY"] = "" #Your Google API Key

    llm = ChatGoogleGenerativeAI(model="gemini-pro",temperature=0.7, top_p=0.85)
    llm_prompt_template = """
以下の入力されたキャラクター（若しくは質問文）について説明（若しくは回答）をしてください。
内容の真偽は曖昧でも良いので何かしら文章を生成してください。
キャラクター（若しくは質問文）: {question} 
回答:"""
    llm_prompt = PromptTemplate.from_template(llm_prompt_template)

    rag_chain = (
        {"question": RunnablePassthrough()}
        | llm_prompt
        | llm
        | StrOutputParser()
        )
    
    simplellm_ans = rag_chain.invoke(question_text)
    
    return simplellm_ans

def ask_rag(question_text):
    
    #RAGの処理
    # Qdrantのベクトルストアを設定
    # 初期化
    os.environ["GOOGLE_API_KEY"] = "" #Your Google API Key

    embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
    client = QdrantClient("localhost", port=6333)

    vector_store = Qdrant(
        client=client,
        collection_name="anpanman_characters",
        embeddings=embeddings
    )

    # リトリーバーの設定
    retriever = vector_store.as_retriever(search_kwargs={"k": 3})

    llm = ChatGoogleGenerativeAI(model="gemini-pro",temperature=0.7, top_p=0.85)
    llm_prompt_template = """
コンテクストに基づいて以下のキャラクター（若しくは質問文）について説明（若しくは回答）をしてください。
キャラクター（若しくは質問文）: {question} 
コンテクスト: {context} 
回答:"""
    llm_prompt = PromptTemplate.from_template(llm_prompt_template)

    rag_chain = (
        {"context": retriever, "question": RunnablePassthrough()}
        | llm_prompt
        | llm
        | StrOutputParser()
        )
    
    rag_ans = rag_chain.invoke(question_text)
    
    references = retriever.get_relevant_documents(question_text)
    print("\n==========RAGの該当部分==========\n")
    for doc in references:
        print(doc.page_content,"\n=============\n")
    
    return rag_ans


def select(request):
    if request.method == 'POST':
        choice = request.POST.get('choice') #選択肢に応じてAI-1 かAI-2を取得する
        if choice == "AI-1":
            message = "Correct !!"
        else:
            message = "Not Correct ..."
        
        context = {
            "your_select": choice,
            "message":message

            }
    else:
        context={

        }
    return render(request, "rag/select.html", context)

rag/templates/rag/base.html
<!doctype html>

<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SB-AI</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <nav class="navbar bg-dark" data-bs-theme="dark">
        <a class="h1 navbar-brand ms-4" href="/">
            <span class="h4 mb-0">SB-AI</span>
            <small class="d-block text-muted">Select Better AI</small>
        </a>
    </nav>

</head>


<body class="bg-warning p-2 text-dark bg-opacity-10">
        <div class="mx-3 mt-2">

            {% block body %}
            {% endblock %}

        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
</body>

    <footer>
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">

        </ul>
        <p class="text-center text-body-secondary">2024 &copy; YT</p>
    </footer>

</html>

rag/templates/rag/index.html
{% extends "rag/base.html" %}

{% block body %}

<h3>-Compare 2 AI, and find better AI !</h3>


<h5 class="my-4 ms-4">(*'▽') 　＜Hi I'm AI-1</h5>

<h5 class=" ms-4">(੭ु´･ω･`)੭ु⁾⁾　＜Hello, I am AI-2</h5>

<div class="my-4">
    <a class="btn btn-primary btn-lg" href="{% url 'rag:llm_quiz' %}">Ask to AI</a>
</div>


{% endblock %}

rag/templates/rag/load.html
{{text}}

<form action="{% url 'rag:load' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="ドキュメントを読み込む" name="loading">
</form>


<form action="{% url 'rag:load' %}" method="post">
    {% csrf_token %}
    <input type="textarea" name="question" placeholder="Enter text for action1 {{question}}">
    <input type="submit" value="RAGに質問する" name = "ask">
</form>


{{answer}}

rag/templates/rag/qa.html
{% extends "rag/base.html" %}

{% block body %}

<h2>Ask 2 AI</h2>
<h5>-- Theme : <u>Anpanman</u></h5>

<div class="mt-4">
  <form action="{% url 'rag:llm_quiz' %}" method="post">
    {% csrf_token %}
    <textarea name="question_text"></textarea>
      <input type="submit" value="Ask to Both" class="btn btn-primary ms-4">
  </form>
</div>


{% if rag_ans %}
<h1 class="mt-3">You Asked : </h1>
<div class="fs-5 fw-bold mt-2 ms-5">
  {{ question_text }}
  {% endif %}
</div>


<h1 class="mt-5">(*'▽')　AI-1 said... </h1>
<div class="fw-bold mt-4 ms-5">
  {% if rag_ans %}
  {{rag_ans | linebreaks }}
  {% endif %}
</div>

<h1 class="mt-5">(੭ु´･ω･`)੭ु⁾⁾　AI-2 said...</h1>
<div class="fw-bold mt-4 ms-5">
  {% if simplellm_ans %}
  {{simplellm_ans | linebreaks }}
</div>


<a href="{% url 'rag:select' %}" class="mt-4 ms-4 btn btn-danger">Selct Better AI</a>
{% endif %}




{% endblock %}

rag/templates/rag/select.html
{% extends "rag/base.html" %}

{% block body %}

<h4 class="mb-4">-Selct the better AI</h4>

<form method="post" action="{% url 'rag:select' %}">
    {% csrf_token %}
    <fieldset>
        <div class="form-check my-2">
            <input class="form-check-input" type="radio" name="choice" id="choice1" value="AI-1" checked>
            <label class="form-check-label" for="choice1">
                <strong> (*'▽') AI-1 </strong>
            </label>
        </div>
        <div class="form-check my-4">
            <input class="form-check-input" type="radio" name="choice" id="choice2" value="AI-2">
            <label class="form-check-label" for="choice2">
                <strong> (੭ु´･ω･`)੭ु⁾⁾ AI-2 </strong>
            </label>
        </div>
        <div>
            <button type="submit" class="btn btn-danger">Check</button>
        </div>
    </fieldset>
</form>


<h4 class="mt-4">Your Select is :　{{your_select}}</h4>
{% if message %}
<h3 class="ms-4">
   <red> {{message}}</red>
</h3>

<h4 class="mt-5">Explanation : </h4>

<p>
    LLM is not always says correct things, 
    it sometimes says the wrong things as if that is completely correct. 
    That is called <strong>"Halluscination"</strong>. Hallucination is often said the <u>big risk</u> of Generative AI.
</p>
<p>
    In this case, Hallcinations were occered in the response of <strong>AI-2</strong>. 
    AI-2 didn't know about Anpanman very well, 
    so they made <u> wrong response</u> when they asked in detail of Anpanman.
</p>
<p>
    On the contrary, <strong>AI-1</strong> made correct answer against the question of Anpanman even if it was very nitch.
    Because AI-1 used the additional data of Anpanman. This technology is call <strong>RAG (Retriever Augmented Generation)</strong>.
    RAG made it possible that makes <u>domain-specific AI</u>.
</p>
<p>
    The point of this explanation is <strong>"LLM does not alwasy tells the correct things"</strong>.
    Did you make sense ? 
</p>
<p>
    Enjoy your AI-Life !!
</p>

{% endif %}

<div class="mt-5">
    <a href="{% url 'rag:llm_quiz' %}" class="btn btn-outline-secondary me-3" role="button">Try Again</a>
    <a href="{% url 'rag:index' %}" class="btn btn-outline-secondary" role="button">Back to the Top</a>
</div>


{% endblock %}